### ISSUE TITLE
Add pre-compiled binaries to releases 

### ISSUE THREAD

**Issue by LucasGGamerM** [pachli/pachli-android#12]
For users (like me) who prefer to live a degoogled life and for now that the Aurora Store is a little flaky, it would be really nice to have a freely available pre built binary.

I have made this issue as the app is not yet on fdroid, which makes getting it without having to deal with Google complicated.

**Comment by nikclayton** [comment]
You're quite right, and thanks for taking the time to point that out. The first release is a little tricky because a lot of the CI machinery I'm putting together assumes there's an existing release to update, rather than starting from no releases.

The GitHub releases page https://github.com/pachli/pachli-android/releases now has the APK attached, and future releases will include that too.

It'll be on F-Droid just as soon as the volunteers there approve and merge https://gitlab.com/fdroid/fdroiddata/-/merge_requests/13682#top (then I think there's a delay until the F-Droid build machinery notices the update).

I think that covers everything, so I'm going to close this now, but please do re-open if anything isn't clear.
