### ISSUE TITLE
When viewing a video a gray overlay covers the video making it hard to see

### ISSUE THREAD

**Issue by ericlathrop** [pachli/pachli-android#144]
**Describe the bug**
When viewing a video a gray overlay covers the video making it hard to see

**To Reproduce**
1. Find a toot with a video
2. Click on the video to open it
3. Witness the gray overlay obscuring the video

**Expected behavior**
I expect to see the unobscured video

**Screenshots or video**
![Screenshot_20231008-122454](https://github.com/pachli/pachli-android/assets/530891/3ef83ede-5d31-4e2d-b35e-1d82b3391346)

**Versions**
Pachli 1.2.1
Android 13

**Affirmation**
X I have checked other issues for this project (open and closed) and I cannot find one that matches the problem I am reporting.

**Comment by nikclayton** [comment]
The overlay should disappear after (IIRC) 5 seconds. It's there so that the controls at the bottom and the media description at the top are visible against whatever background the video might provide (e.g., suppose the video opened with a few seconds of a white or very pale background).

Is the overlay not disappearing for you?

Or are you suggesting that the overlay, media controls, and media description should not be shown by default, and the user should have to touch the screen first to get them to appear?

**Comment by ericlathrop** [comment]
Oh, it does actually disappear after 5 seconds. I have the attention span of a hummingbird so I've never seen that until you told me. Still, I think it's too intrusive, and I miss the beginnings of videos.
