### ISSUE TITLE
Changing a list's name is not reflected in the relative home tab

### ISSUE THREAD

**Issue by fourlastor** [pachli/pachli-android#192]
**Describe the bug**
When changing a list name, the relative tab in home (if it was previously added) is not updated. It can be worked around by removing and re-adding the list as a tab.

**To Reproduce**
1. Go to the Lists page
2. Create a new list, setting a name
3. Go to the Account preferences page
4. Go to the Tabs page
5. Add the created list to the home tabs
6. Go back to the list page
7. Select "Update the list" from the 3-dots menu
8. Rename the list

**Expected behavior**
The list name is updated in home as well.

**Screenshots or video**
| List seen from list page | List seen as a home tab | 
| --- | --- |
| ![Screenshot_20231021-193354](https://github.com/pachli/pachli-android/assets/1263058/034f76f8-f7f8-4517-9afc-c021d0fbfff4) | ![Screenshot_20231021-193346](https://github.com/pachli/pachli-android/assets/1263058/db220f7c-abac-4df5-8c37-e97c3aa14ec8) |

**Links**
N/A

**Versions**
Android 12 (Google Pixel 3a)
Pachli 1.2.2

**Additional context**
N/A

**Affirmation**
I have checked other issues for this project (open and closed) and I cannot find one that matches the problem I am reporting.

**Comment by nikclayton** [comment]
Thanks for the report and clear reproduction instructions/screenshots.

**Comment by nikclayton** [comment]
Note to self after looking in this a bit.

More complex than it looks at first sight, because the name of the list is stored alongside the list ID in `AccountEntity.tabPreferences`.

Now that there's a `ListsRepository`, lists are fetched at startup, and Moshi makes polymorphic JSON serialisation pretty easy the correct way to solve this is probably:

- [ ] Change the tabPreferences serialisation format to be polymorphic Json (`Converters.tabDataToString`), and update `Converters.stringToTabData` to read both old and new format.
- [ ] Remove the list's title from the data that's serialised, so the server's value is always used.
- [ ] Amend the code in `MainActivity` that collects from `ListsRepository` to regenerate the tabs
