### ISSUE TITLE
Network activity toward content-autofill.googleapis.com

### ISSUE THREAD

**Issue by Porkepix** [pachli/pachli-android#223]
**Describe the bug**
Can't tell exactly how much Pachli's can act around this; it seems to be related to the login process to your Fediverse account, so this might be pulled in from Android's webview, can't tell for sure but I preferred open an issue in case.

**To Reproduce**
Login a Fediverse account, and have something to see network activity

**Expected behavior**
This shouldn't connect to anything Google related

**Screenshots or video**
<details>
<summary>
Screenshot from TrackerControl
</summary>

![Screenshot_20231105-174305](https://github.com/pachli/pachli-android/assets/709500/541cb855-616c-4d97-aab8-4ad8bdb15cd6)

</details>

**Versions**
Latest release from F-droid (1.2.2) on Android Oreo (8.0), stock build

**Affirmation**
I have checked other issues for this project (open and closed) and I cannot find one that matches the problem I am reporting.

**Comment by nikclayton** [comment]
Thanks for the report.

Since this isn't something Pachli is doing directly some research led me to https://android-developers.googleblog.com/2017/11/getting-your-android-app-ready-for.html, and in particular this line:

> If you use WebViews in your app, which many apps do for logins and other screens, your users can now also benefit from Autofill support, as long as they have Chrome 61 or later installed. 

If you check your Android system settings do you have an autofill service enabled? If so, and you disable it, does the network traffic to content-autofill.googleapis.com stop?

Assuming it does, I don't think this is something that Pachli should configure differently, for the following reasons.

1. There's already a user control to disable this provided by Android
2. Disabling a feature used by password managers at the point where users are entering passwords
 feels like a bad idea -- this is the sort of thing that drives users to choose poor passwords because they are easier to remember and/or type on a mobile keyboard

**Comment by nikclayton** [comment]
Do you still see the network traffic even with that "Use Autofill with Google" option toggled odd?

**Comment by nikclayton** [comment]
I've just tried this in an emulator running Oreo (API level 26).

On the "Languages and Input" screen (your first screenshot) I can get to your second screenshot by pressing the "cog" icon on the right of the "Autofill service" item. You're correct, that has no option to set the autofill service to "None".

However, on the "Languages and Input" screen if I press on the left of the "Autofill service" item (i.e., *not* the cog, the text) then I get to the screen that allows for it to be set to "None".

![image](https://github.com/pachli/pachli-android/assets/773100/b4fd11af-1c3c-4647-b1d1-265c7b70cca3)

**Comment by nikclayton** [comment]
OK. I'm comfortable closing this, given that:

1. The network traffic isn't coming from Pachli
2. The user has a mechanism for turning it off at the Android level
3. The default behaviour enables password autofill, which helps users avoid bad passwords
