### ISSUE TITLE
Green edited parts are not displayed using selected font, but system default.

### ISSUE THREAD

**Issue by jumase** [pachli/pachli-android#435]
**Describe the bug**
When viewing editions on any edited post, the red part is rendered correctly but the green text is shown with system default font.

**To Reproduce**
1. You need to be using any of the "alternative" fonts that are bundled with Pachli, for example Atkinson Hyperlegible.
2. Search for any edited post (look for an asterisk next to the post time).
3. Open it and then click on the "Edited _date&time_" at the bottom of the post.
4. See the issue.

**Expected behavior**
Green edited text should be rendered with selected font, being bold or simply green background.

**Screenshot**
See the letter "i" on the screenshot, it's quite noticeable.
![Screenshot_Pachli](https://github.com/pachli/pachli-android/assets/96543724/5a7827c5-35e4-4d09-846b-bb124071cb38)

**Link**
Example from https://social.growyourown.services/@FediTips/111919512557652940

**Versions**
Pachli 2.2.0
Android 10
Mastodon 4.2.5

**Additional context**
I tried also with Comic Neue font and the issue still persists.

**Affirmation**
I have checked other issues for this project (open and closed) and I cannot find one that matches the problem I am reporting.

**Comment by nikclayton** [comment]
Thanks for the report, I'll have a fix for this shortly.

While I've got your attention, please can you sign the CLA so that we can accept your translation contributions (see https://github.com/pachli/pachli-android/pull/437#issuecomment-1943452996).

And if you'd like to be credited in the release notes with your Mastodon username please can you add it here too. Thanks!

![image](https://github.com/pachli/pachli-android/assets/773100/dd4a0d7f-ea6a-43de-b4e6-9727874d94a3)
