### ISSUE TITLE
Cannot log into Pachli

### ISSUE THREAD

**Issue by myfta** [pachli/pachli-android#638]
New install on an Asus tablet. Cannot login to Pachli, authentication fails "Failed authenticating with that instance"

**To Reproduce**
1. Fresh install (no errors during install.
2. Login screen, enter instance name, click "LOGIN WITH PACHLI"
3. Return an arror "Failed authenticating with that instance"

**Expected behavior**
Logged in. (It does work on a Moto G10 phone.)

**Versions**
Pachli 2.4.0
Android 7.0

I have checked other issues for this project (open and closed) and I cannot find one that matches the problem I am reporting.

**Comment by nikclayton** [comment]
What's the instance name?

**Comment by myfta** [comment]
mastodon.green

Thanks

**Comment by nikclayton** [comment]
I think this is a security certificate problem.

# Background

When your device connects to the server (mastodon.green) the server sends back a security certificate that says "I really am mastodon.green, you can trust me".

That's not enough on its own, otherwise anyone could create a certificate that says the same thing.

To fix this, the certificate is created by a "Certificate Authority" (CA), and it's up to the CA to verify that they only create legitimate certificates.

This just pushes the problem back a stage further; how does your device know that it can trust the CA? One way to do that, and the way that Android 7 does it, is to have a hard-coded list of CAs. If your device sees a certificate issued by that CA it trusts it, and if it's from a CA that's not on the list then it refuses to connect.

# Problem

The server (mastodon.green) is using a certificate issued by the CA "Let's Encrypt". Nothing wrong with that, they're a great CA.

However, Let's Encrypt is not one of the CAs on the Android 7 hard-coded list of CAs.

To fix this, Let's Encrypt **used to** have their certificate cross-signed by IdenTrust, another CA.

Android 7 trusts IdenTrust, IdenTrust trust's Let's Encrypt, so Android 7 trusted the certificates from Lets Encrypt.

This has changed. In 2020 Let's Encrypt started a process that meant older devices (including Android 7) would eventually stop trusting their certificates (https://letsencrypt.org/2020/11/06/own-two-feet).

Let's Encrypt has finished that process (https://letsencrypt.org/2023/07/10/cross-sign-expiration.html), and now Android 7 no longer trusts their certificate.

Which is why you get the "Failed authenticating with that instance" error.

# Solution

Right now you can try the procedure at https://www.stoutner.com/lets-encrypt-isrg-root-x1-and-privacy-browser/. I haven't tested that (I don't have a device with the problem), so that's at your own risk.

If that does work for you please let me know.

In the meantime I'm going to see if it's possible to add the Lets Encrypt certificates to Pachli so it will trust them.

**Comment by myfta** [comment]
The certificate installs correctly as per the instructions and validates on the Let's Encrypt test page. 

However, it does not fix the Pachli login issue.

**Comment by nikclayton** [comment]
Thanks.

Are you able to install a test version from an APK file?

If so, the APK file attached to the comment at  https://github.com/pachli/pachli-android/pull/640#issuecomment-2072885187 might fix this.

**Comment by myfta** [comment]
I can confirm your new release fixed the Let's Enrypt issue. 

So I'll stick with this version until your released Play Store version catches up?

**Comment by nikclayton** [comment]
Thanks for the confirmation.

If you have the time, would you be able to remove the certificates that you manually installed, and see if it still works. The version of Pachli in that APK includes a copy of the certificates, so I'd like to know if that bit is working as well.

You can continue using that version for a week (there'll be a new release this week that includes the fix in the version you're using) but after that you should definitely switch to one of the official releases, as the version you currently have installed cannot be updated via Google Play.

**Comment by myfta** [comment]
I've removed that certificate and the patched version still works.
Thanks.
