### ISSUE TITLE
App tells me there is a new version on F-Droid when there isn't

### ISSUE THREAD

**Issue by Andre601** [pachli/pachli-android#684]
**Describe the bug**
When I open the app does it notify me of a new version.
Opening f-droid and refreshing it does however not show any new update...

**To Reproduce**
1. Just open the spp.

**Expected behavior**

**Screenshots or video**

**Links**

**Versions**
Pachli 2.4.0

Device:

samsung SM-G960F 
Android-Version: 10 
SDK-Level: 29

Account:

@andre_601@blobfox.coffee 
Version: 4.3.0-alpha.3+glitch+blobfox

**Additional context**

**Affirmation**
I have checked other issues for this project (open and closed) and I cannot find one that matches the problem I am reporting.

**Comment by nikclayton** [comment]
Hmm, something's odd at F-Droid.

If I fetch https://f-droid.org/api/v1/packages/app.pachli I get back this:

```json {"packageName":"app.pachli","suggestedVersionCode":15,"packages":[{"versionName":"2.4.0","versionCode":13},{"versionName":"2.3.0","versionCode":12},{"versionName":"2.2.0","versionCode":11}]}
```

I don't know why the API response is suggesting versioncode 15 (correct) without a block that includes the version name as well.

But, this does at least confirm that F-Droid is returning v15 as the newest version. Since that's newer than the version you have installed (v13, which is Pachli 2.4.0) you're getting the update prompt.

I'm on vacation at the moment, so can't investigate further right now (back in a couple of weeks), but I'll mention this on the F-Droid dev chat in case one of them can follow up / investigate on the F-Droid side.

**Comment by Andre601** [comment]
> I don't know why the API response is suggesting versioncode 15 (correct) without a block that includes the version name as well.

My best guess would be the classic case of "action failed successfully", like the build may have failed, but it still was considered a successful run, so the version was updated while the content wasn't...
Alternative idea is, that this may be a bad case of broken caching...

**Comment by mat-l** [comment]
The F-droid build status app shows, that it was not able to connect to your git:
![Screenshot_20240508_073305_de storchp fdroidbuildstatus](https://github.com/pachli/pachli-android/assets/5571947/26777470-3aa5-4124-9d7a-6154b5f1f020)
![Screenshot_20240508_073311_de storchp fdroidbuildstatus](https://github.com/pachli/pachli-android/assets/5571947/f02db92e-fbf3-4b8f-9190-1f751840892e)

**Comment by nikclayton** [comment]
@mat-l Thanks, I got some of the same feedback on the F-Droid chat.

https://gitlab.com/fdroid/fdroidserver/-/issues/1210 is an open issue for this. When I'm back (and once I've had confirmation about the correct algorithm to use to reliably check for the update) I'll update Pachli to use it.

**Comment by Andre601** [comment]
I'm tempted to comment on the issue and propose a `/packages/<package>/versions` endpoint that would return a json scheme like this:
```json5
{
    "latest": 2, // latest set version
    "latestAvailable": 1 // latest available in packages
}

**Comment by nikclayton** [comment]
Note to self: the correct algorithm to use to determine an installable version code using the F-Droid API is:

- Call the API
- If `suggestedVersionCode` is in the `packages` list, use that
- Otherwise, sort the list of `packages` by version code, use the highest version code

That's consistent with how e.g. shields.io performs version checks, see https://github.com/badges/shields/blob/master/services/f-droid/f-droid.service.js

**Comment by Andre601** [comment]
Could the version be manually fixed for now (either by getting a new file submitted or by having f-droid fix it on their end)?

Because while this is being looked at, discussed and eventually fixed am I still getting these notifications, even when I tell the app to ignore this particular version... It would REALLY help me.

**Comment by nikclayton** [comment]
> Could the version be manually fixed for now (either by getting a new file submitted or by having f-droid fix it on their end)?
> 
> Because while this is being looked at, discussed and eventually fixed am I still getting these notifications, even when I tell the app to ignore this particular version... It would REALLY help me.

In Preferences (at the bottom) you can disable update checks.

**Comment by n2burns** [comment]
> There is an option to skip prompts for a specific version (or only show the prompt once) which might help.

I'm not sure if this is related to this issue, but that option doesn't work for me. Every few days, the prompt shows up again.

**Comment by Andre601** [comment]
Yeah, it's an issue, because I mentioned that myself:

> Because while this is being looked at, discussed and eventually fixed am I still getting these notifications, even when I tell the app to ignore this particular version... It would REALLY help me.

**Comment by nikclayton** [comment]
2.5.1 is now available in F-Droid.

**Comment by Andre601** [comment]
Thanks, updated the app.
