### ISSUE TITLE
Translation support isn't recognized for non-Mastodon servers

### ISSUE THREAD

**Issue by mileskrell** [pachli/pachli-android#714]
**Describe the bug**
Translation isn't available on my home server `tech.lgbt`, which is running Glitch. This server supports translation, but the current implementation of [Server.from](https://github.com/pachli/pachli-android/blob/f689ea8f2106cff40d79cb0d50ec5d9fcc66927c/core/network/src/main/kotlin/app/pachli/core/network/Server.kt#L110-L131) disallows translation for non-Mastodon servers regardless of the value of `configuration.translation.enabled`.

**To Reproduce**
The following video first shows that the translation option ("Traducir") is missing when using an account on `tech.lgbt`, and then shows that the translation option is present when using an account on `mastodon.social`.

https://github.com/pachli/pachli-android/assets/16272279/00288d2d-b124-46a8-abf0-969292481d95

**Expected behavior**
Ideally, the translation feature should be available for any server that supports it. The Mastodon docs [say](https://docs.joinmastodon.org/entities/Instance/#translation-enabled) that translation support is indicated by setting `configuration.translation.enabled` to true in the response from `/api/v2/instance`. But other server types could indicate translation support in other ways, so we should see what we can find in the docs for other server types before enabling translation for all servers based on this attribute. We might end up only enabling it for Glitch and other Mastodon forks.

**Versions**
Pachli Current 2.5.1+23301213
Android 14
Server where translation option is missing: 4.3.0-alpha.3+glitch

**Affirmation**
I have checked other issues for this project (open and closed) and I cannot find one that matches the problem I am reporting.

**Comment by nikclayton** [comment]
Good point. I'll include the Glitch server type when looking for translation support.

https://socialhub.activitypub.rocks/t/fep-9fde-mechanism-for-servers-to-expose-supported-operations/3999 is how I'd like to solve the problem more generically...

**Comment by ShadowJonathan** [comment]
FWIW, Glitch-soc is almost always a superset of mastodon in terms of server support. glitch implies mastodon, so to speak. But I don't know if that's something this project has ran into before, or if there's subtleties im missing :)

**Comment by mileskrell** [comment]
A few more server types also indicate translation support via `configuration.translation.enabled` in the response from `/api/v2/instance`:
- Hometown (another Mastodon fork) - [example](https://hcommons.social/api/v2/instance)
- Pixelfed - [example](https://pixelfed.social/api/v2/instance)
- GoToSocial - [docs](https://docs.gotosocial.org/en/latest/api/swagger/), [example](https://meow.day/api/v2/instance)

We should be able to add support for these in addition to Glitch. Though it's unclear for non-forks like Pixelfed and GoToSocial what version range supports this feature, which poses a barrier for adding support given that our current code hardcodes this info. (On that note, [this version-checking code](https://github.com/pachli/pachli-android/blob/dd2efe97955449d4f1cd336ef4e51e62467437b0/core/network/src/main/kotlin/app/pachli/core/network/Server.kt#L120-L125) seems redundant to me? It reads to me like "if this instance supports translation, then record the fact that this server type supports translation if it's within a specific version range", but if `configuration.translation.enabled` is true, isn't it already implied that the server must be within the version range that supports translation? It might just be an oversight or I might be missing something.)

Misskey doesn't support this endpoint but the [Misskey docs](https://misskey.io/api-doc#tag/meta/operation/meta) make it sound like you can check for translation support via the `translatorAvailable` property in the response from `POST /meta` (e.g. `curl -X POST -d '{}' -H 'content-type: application/json' 'https://misskey.io/api/meta'`). But I'm not in a rush to add support for that endpoint until we've added support for emoji reactions since until then, folks using Misskey and its forks like Sharkey/Firefish/Iceshrimp probably won't use Pachli anyway.

It's unclear to me how to check for post translation support on other server types (if there are any others that support it).

**Comment by nikclayton** [comment]
@ShadowJonathan Thanks.

@mileskrell I've added Hometown to the list that can be checked for translation. Pixelfed isn't officially supported, e.g., the notification API implementation has problems, https://github.com/tuskyapp/Tusky/issues/3580#issuecomment-1527198806. There's a constant for it in the code to remind me to go back and disable the notification functionality at some point. GoToSocial provides the configuration block but it's permanently set to `false`.

> (On that note, [this version-checking code](https://github.com/pachli/pachli-android/blob/dd2efe97955449d4f1cd336ef4e51e62467437b0/core/network/src/main/kotlin/app/pachli/core/network/Server.kt#L120-L125) seems redundant to me? It reads to me like "if this instance supports translation, then record the fact that this server type supports translation if it's within a specific version range", but if configuration.translation.enabled is true, isn't it already implied that the server must be within the version range that supports translation? It might just be an oversight or I might be missing something.)

The Mastodon translation API has changed over time. So there's two different versions at play; (a) the version number of the server, and (b) the version number of the API call the server implements.

Checking `configuration.translation.enabled` tells you if the server supports the translation API (i.e., "a", above) but does not tell you which version of the API it supports (i.e., "b" above). So you need to check both.

For the specific case of the translation API this is overkill, since the different versions of the translation API only differ in what they return.

But the Mastodon developers have a history of adding new features to APIs without bumping the public API version number (e.g., https://docs.joinmastodon.org/methods/timelines/#public) so I decided a mechanism to represent this in the capabilities was necessary.

**Comment by mileskrell** [comment]
SGTM, thanks @nikclayton!

**Comment by nikclayton** [comment]
Just verified the new code enables translation on tech.lgbt.
