### ISSUE TITLE
Loading indicator showing indefinitely on Home TL

### ISSUE THREAD

**Issue by tinsukE** [pachli/pachli-android#75]
**Describe the bug**
A loading indicator was showing indefinitely on the Home TL. This happened after launching the app from a Follow Request push notification.

Pulling to refresh quickly cleared the loading indicator.

**To Reproduce**
I'm not sure this will happen every time, but this is how it happened for me:
1. Receive a Follow Request notification
2. Click on it
3. Accept the request
4. Press the back button until back to the Home TL
5. See a loading indicator that doesn't dismiss/end

**Expected behavior**
The loading indicator should disappear when loading is finished

**Screenshots or video**

https://github.com/pachli/pachli-android/assets/1063155/c971daf3-4cdb-46f5-a8d1-7b33abb39d62

**Versions**
- Pachli: 1.1
- Server: 4.1.8
- Android 13

**Affirmation**
I have checked other issues for this project (open and closed) and I cannot find one that matches the problem I am reporting.

**Comment by nikclayton** [comment]
Thanks for the report (and the video, that's very helpful).

How long did you wait for before refreshing?

The network timeout is 30 seconds. I've seen a similar issue when I've got a device (real or emulated) connected, and the logs show that the app is legitimately waiting for a network request to complete (typically the request to refresh the timeline). While the request is in flight the spinner is shown.

Swipe-refresh as you do in the video cancels the request and starts a new one. So if you got unlucky and your server didn't quickly respond to the first request but did respond quickly to the second one you get the behaviour in the video.

This isn't great UI for a couple of reasons:

1. The progress spinner in the middle of the screen. I'm tempted to just remove that, and always use the smaller "swipe refresh" spinner, since it's probably a better indicator of "a refresh is happening", instead of having two different UI elements that mean the same thing.

2. The network timeout. Maybe 30 seconds is too high for non-image requests.

**Comment by tinsukE** [comment]
I've gotta say that I didn't count and that I waited initially long enough (maybe 10s?) for it to feel too long and then thought about recording.

But indeed, it could be network or server latency. I'll make sure to wait at least 30s if/when next time it happens and update the issue accordingly.

**Comment by nikclayton** [comment]
Thanks. I'll leave this open for the moment to keep track of the issue.

**Comment by foss-** [comment]
In my test no post ever loaded for a friendica account I was trying to use with Pachli 1.1. Pachli shows `A network error occurred: timeout`. When tapping Retry nothing happens.

Logged out of the account in question and re-added it, but that resulted in the same behavior. Instance is pirati.ca.

The error shows exactly 30 seconds after initiating loading posts.

The friendica account not loading posts: This is Friendica, version 2023.09-dev that is running at the web location https://pirati.ca. The database version is 1535/1535, the post update version is 1507/1507.

Friendica acount which loads posts: This is Friendica, version 2023.09-dev that is running at the web location https://squeet.me. The database version is 1532/1532, the post update version is 1507/1507.

**Comment by nikclayton** [comment]
@foss- : What you describe would be consistent with pirati.ca and squeet.me having occasional outages or networking blips, or your device is having a brief issue connecting to them. If this happens again checking with another app (browser would be best). If you can contact the admins of those servers and ask if they had any outages at the time you were checking that would be helpful too.

The "timeout" message is coming from inside the networking library that Pachli uses, and indicates that the remote server either did not read the request from Pachli within 30 seconds, or did not provide a response within 30 seconds.

**Comment by foss-** [comment]
I had tested webUI and it was reachable fine ans still is. While pirati.ca does not allow public sign up, public posts can be reached e.g. https://pirati.ca/display/52acf9cd-cd7cc455dfa54f19-bb7a7874

So while webUI can be reached fine, no posts at all will load in Pachli. Reached out to the admin and will share once I get feedback from them.

**Comment by prohr** [comment]
I'm also occasionally getting the indefinite loading indicator.   Trigger seems to be falling too far behind the chronological timeline.  The post I was on disappears, the view jumps ahead in time to the oldest available post window, and the infinite loading indicator appears.

Note that the indicator stays onscreen for well over 30 minutes, so this may have a different root cause than other reports above.   My usual workaround is to close + reopen the app so I don't lose my scroll position, but LMK if there's anything else you want me to try the next time this happens.

**Versions**

Pachli: 1.2.2
Android: 13
SDK: 33
Server: 4.2.1

**Comment by prohr** [comment]
Update with more details.  When this happened tonight, the triggering behavior seemed to be a switch from day to night mode (in keeping with the "Automatic at sunset" App theme).  I wasn't far enough behind to trigger a jump ahead in time, but other recent arrivals may have shown up.

A manual refresh cleared the infinite reloading indicator.
