### ISSUE TITLE
Pachli freezes after adding the 6th account

### ISSUE THREAD

**Issue by flberger** [pachli/pachli-android#752]
**Describe the bug**
When I add the 6th account to Pachli, the app closes. Upon re-opening, the app does not open, instead Android yields "Pachli is being repeatedly closed". After wiping all local data, Pachli can be started again, 5 accounts can be added again with ease, but same behaviour on the 6th account. The order of adding the accounts apparently has no influence.

**To Reproduce**
1. Add an account to Pachli.
2. Add another account to Pachli.
3. Add another account to Pachli.
4. Add another account to Pachli.
5. Add another account to Pachli.
6. Add another account to Pachli. Observe the behaviour described above.

**Expected behavior**
Pachli should continue to function when adding numerous accounts, just as its root Tusky did.

**Screenshots or video**
![Screenshot_20240609-164301](https://github.com/pachli/pachli-android/assets/8035998/9c93b55d-f235-4ce2-b582-afe3f7bab1ab)

**Versions**
- Android 9 on Fairphone 2
- Pachli 2.5.2 from F-Droid
- various, usually quite recent servers:
    - nerdculture.de
    - chaos.social
    - social.anoxinon.de
    - floss.social
    - mastodontech.de

**Affirmation**
I have checked other issues for this project (open and closed) and I cannot find one that matches the problem I am reporting.

**Comment by nikclayton** [comment]
Thanks for the report, sorry this is affecting you.

Can you reproduce this in Pachli Current (https://pachli.app/download/#pachli-current) ? I've got 7 accounts added at the moment and it's working fine.

If you can reproduce the crash in Pachli Current you'll be prompted to share a crash report by e-mail. If you can do that it'll help me narrow down the problem.

**Comment by flberger** [comment]
I can reproduce the exact same behavior with Pachli Current:

![Screenshot_20240619-205332](https://github.com/pachli/pachli-android/assets/8035998/c8b49121-ef38-48a6-960c-cd3f84a5fcd6)

But I am not prompted to send a report. I suspect the app is being killed before that can happen.

As a Linux person, this has vibes of an OOM kill. The device is relatively short on RAM, but then again, why should this strike after only 6 accounts.

How do we proceed?

**Comment by nikclayton** [comment]
[Speculation]

When you add an account Pachli creates a "shortcut" (long-press the app icon to see them) to the account.

Different devices / Android versions have different caps on the maximum number of accounts that can be created, and it was being exceeded here.

For reasons I can't quite fathom it was decided that exceeding this limit should throw an exception instead of returning an error, and that's what's causing the crash.

I can reproduce this crash on an emulator configured like your Fairphone 2

I'm going to submit the change and deploy a new version of Pachli Current that includes it. That might take a few hours for Google to approve. You'll know it's been updated when https://play.google.com/store/apps/details?id=app.pachli.current shows the app as updated on the 20th and the "What's new" entry says "fix: Don't exceed the maximum number of created shortcuts".

When you see that please can you update and try adding the accounts again. Assuming that solves the problem the fix will be in the next full Pachli release, which should be later next week.

Thanks again for reporting this, and helping to track down the problem.

**Comment by nikclayton** [comment]
The new Pachli Current is now available on Google Play.

**Comment by flberger** [comment]
Fix confirmed: After the update, Pachli Current starts normally, instead of being closed. I could then another account and use a total of 7 without issues.

I would welcome the fix in the next regular Pachli release.
